### ISSUE TITLE
Is there any way to render sdf glyphs to image?

### ISSUE THREAD

**Issue by jingsam** [mapbox/fontmachine#10]

**Comment by mikemorris** [comment]
_Should be possible, I just don't have sample code to point you to for rendering to static image formats._

Our implementations for rendering text from SDFs in WebGL/OpenGL live in https://github.com/mapbox/mapbox-gl-native/ and https://github.com/mapbox/mapbox-gl-js/, and we wrote a blog post about how we render from SDFs at https://www.mapbox.com/blog/text-signed-distance-fields/.

You could also check out the original published paper by Valve Software at http://www.valvesoftware.com/publications/2007/SIGGRAPH2007_AlphaTestedMagnification.pdf

**Comment by jingsam** [comment]
Right now, I'm trying implement a feature to preview sdf fonts. Is it ok to tell me how mapbox studio implement this feature?

**Comment by mikemorris** [comment]
@jingsam Ah, neat. Mapbox Studio displays images generated server-side through the Node.js bindings to mapbox-gl-native - it's possbile that a simpler solution would be better for your use case.

**Comment by jingsam** [comment]
I just figure out to generate fonts images using node-canvas. This is simpler but it needs ttf or otf fonts

**Comment by mikemorris** [comment]
@jingsam Yea, one reason we're using SDFs is to avoid having to transmit an entire font file to a user to render labels from a limited number of glyphs. Something like https://mattdesl.github.io/canvas-text/ might be an option for your use case?

**Comment by jingsam** [comment]
Thanks a lot. I think it would be better to extract the text rendering engine of mapbox-gl to a seperated package.

**Comment by lbud** [comment]
@jingsam if you're still looking for a solution for this, [glyph-inspect](https://github.com/mapbox/glyph-inspect) is a small util to inspect glyph metadata and includes an `--html` option to write out a (very crude) HTML file that renders individual glyphs to canvases. (The rendering is also crude, not intended to reimplement Mapbox GL rendering but rather just give a simple idea of what a glyph looks like.)

![image](https://cloud.githubusercontent.com/assets/3170312/17264720/c04c19e0-559d-11e6-8b92-29e0aaa4f53b.png)
