### ISSUE TITLE
can't donwload gz from aws

### ISSUE THREAD

**Issue by rroset** [mapbox/fontmachine#7]
Trying to install fontmachine to produce our own glyphs, all I get is

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbo
x-node-binary.s3.amazonaws.com/fontnik/v0.4.4/node-v46-win32-ia32.tar.gz

Pasting the failing URL 
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>825BE3E4E7398F36</RequestId><HostId>2JPlI2GfGByQ1bGkFSAA3iyUF49JbHZUufYzFt0bmrGVYqy+f6VszPbFA90oTVpP</HostId></Error>

**Comment by mikemorris** [comment]
Mmm, guessing from the node-pre-gyp URL that you're on a Windows machine. We haven't done any testing, let alone published binaries for Windows. It looks like [there may be a Windows distribution of Freetype](http://www.freetype.org/download.html) - if you're up for trying to add Windows support, a pull request would be welcomed.

**Comment by rroset** [comment]
not sure if it is tied to windows alone: got the same error on ubuntu under virtualbox. Besides if I paste the URL directly in a browser window I get the same error message

**Comment by mikemorris** [comment]
@rroset Well the error is because a binary for that architecture (a file at that path) doesn't exist - the error message could probably be more clear. On Ubuntu you can try running `npm install --build-from-source fontnik` - it's possible there isn't a [precompiled binary available for your specific version/architecture](https://github.com/mapbox/node-fontnik#installing) (it looks you might be on a 32-bit machine?)

**Comment by rroset** [comment]
"(it looks you might be on a 32-bit machine?)" nope it was a 64bit one.
No worries, on monday I'll install under a native 64 bit ubuntu vmbox and I'll get back. thanks anyway

**Comment by mikemorris** [comment]
Ah, I was a bit off - `ia32` in the URL indicates a 32-bit version of Node.js (which does run fine on a 64-bit machine). You can download a Linux 64-bit Node.js binary from https://nodejs.org/en/download/. Alternatively, building `fontnik` from source on Linux should work as well.

**Comment by rroset** [comment]
I stand corrected, works fine on a vm with ubuntu 64. Only precaution is to apt-get install nodejs-legacy
thanks

**Comment by mikemorris** [comment]
@rroset Glad you got it working! FWIW, using apt-get to install Node.js is a bit of a mess, as the published versions I've seen are several years outdated. I'd recommend using https://github.com/creationix/nvm
